source_db:
  dialect: mysql+pymysql
  host: localhost
  port: 3306
  username: root
  password: password
  database: vtc3plcom_vtcdb

target_db:
  dialect: mysql+mysqlconnector
  host: localhost
  port: 13306
  username: root
  password: password
  database: terpdb